create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(254) not null,
    password_hash varchar(100) not null,
    display_name  varchar(20)  not null,
    invite_code   varchar(8)   not null,
    created_at    timestamptz  not null,
    constraint users_email_uk unique (email),
    constraint users_invite_code_uk unique (invite_code)
);

-- One row per direction: "my friends", "are we friends" and friend counts are single index lookups (no unions).
create table friendships (
    user_id    bigint      not null references users (id) on delete cascade,
    friend_id  bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    primary key (user_id, friend_id),
    constraint friendships_not_self check (user_id <> friend_id)
);
create index friendships_friend_idx on friendships (friend_id);

create table moments (
    id         bigint generated by default as identity primary key,
    sender_id  bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null
);
create index moments_sender_idx on moments (sender_id, id desc);

-- Audience snapshot taken at post time; visibility additionally requires a current friendship with the sender.
create table moment_recipients (
    moment_id    bigint not null references moments (id) on delete cascade,
    recipient_id bigint not null references users (id) on delete cascade,
    primary key (moment_id, recipient_id)
);
create index moment_recipients_recipient_idx on moment_recipients (recipient_id, moment_id desc);

create table reactions (
    id         bigint generated by default as identity primary key,
    moment_id  bigint      not null references moments (id) on delete cascade,
    user_id    bigint      not null references users (id) on delete cascade,
    emoji      varchar(16) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint reactions_moment_user_uk unique (moment_id, user_id)
);
create index reactions_user_idx on reactions (user_id);

create table comments (
    id         bigint generated by default as identity primary key,
    moment_id  bigint       not null references moments (id) on delete cascade,
    author_id  bigint       not null references users (id) on delete cascade,
    text       varchar(100) not null,
    created_at timestamptz  not null
);
create index comments_moment_idx on comments (moment_id, id);
create index comments_author_idx on comments (author_id);

create table messages (
    id          bigint generated by default as identity primary key,
    sender_id   bigint       not null references users (id) on delete cascade,
    receiver_id bigint       not null references users (id) on delete cascade,
    moment_id   bigint       references moments (id) on delete set null,
    text        varchar(500) not null,
    created_at  timestamptz  not null,
    read_at     timestamptz
);
-- Thread lookups use the unordered pair, so both directions share one index range.
create index messages_pair_idx on messages (least(sender_id, receiver_id), greatest(sender_id, receiver_id), id desc);
create index messages_sender_idx on messages (sender_id);
create index messages_receiver_idx on messages (receiver_id);
create index messages_unread_idx on messages (receiver_id, sender_id) where read_at is null;
create index messages_moment_idx on messages (moment_id) where moment_id is not null;

create table device_tokens (
    id          bigint generated by default as identity primary key,
    token       varchar(200) not null,
    user_id     bigint       not null references users (id) on delete cascade,
    kind        varchar(10)  not null,
    environment varchar(12)  not null,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null,
    constraint device_tokens_token_uk unique (token),
    constraint device_tokens_kind_ck check (kind in ('app', 'widget')),
    constraint device_tokens_environment_ck check (environment in ('development', 'production'))
);
create index device_tokens_user_idx on device_tokens (user_id);
