-- Group chats. Everyone in a group must be friends with everyone else when it is created.
create table chat_groups (
    id         bigint generated by default as identity primary key,
    name       varchar(30),
    created_by bigint      references users (id) on delete set null,
    created_at timestamptz not null
);

-- last_read_id: the newest group message this member has seen (0 = none); unread counts and read receipts come from it.
create table chat_group_members (
    group_id     bigint      not null references chat_groups (id) on delete cascade,
    user_id      bigint      not null references users (id) on delete cascade,
    last_read_id bigint      not null default 0,
    joined_at    timestamptz not null,
    primary key (group_id, user_id)
);
create index chat_group_members_user_idx on chat_group_members (user_id);

create table group_messages (
    id         bigint generated by default as identity primary key,
    group_id   bigint       not null references chat_groups (id) on delete cascade,
    sender_id  bigint       not null references users (id) on delete cascade,
    text       varchar(500) not null,
    created_at timestamptz  not null
);
create index group_messages_group_idx on group_messages (group_id, id desc);
create index group_messages_sender_idx on group_messages (sender_id);
