-- 차단: blocker 가 blocked 를 막았다. 친구가 끊기고 다시 친구가 될 수 없으며, blocker 에게는 blocked 의 댓글 · 대화 · 단챗 메시지가 안 보인다.
create table blocks (
    blocker_id bigint      not null references users (id) on delete cascade,
    blocked_id bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    primary key (blocker_id, blocked_id),
    constraint blocks_not_self check (blocker_id <> blocked_id)
);
create index blocks_blocked_idx on blocks (blocked_id);

-- 신고: 운영자가 확인하고 처리한다 (/api/admin/reports). snapshot 은 신고 당시의 글 (원본이 지워져도 볼 수 있게).
create table reports (
    id             bigint generated by default as identity primary key,
    reporter_id    bigint       references users (id) on delete set null,
    target_user_id bigint       references users (id) on delete set null,
    kind           varchar(16)  not null,
    target_id      bigint,
    reason         varchar(16)  not null,
    detail         varchar(500),
    snapshot       varchar(600),
    created_at     timestamptz  not null,
    resolved_at    timestamptz,
    resolution     varchar(200),
    constraint reports_kind_ck check (kind in ('moment', 'comment', 'message', 'group-message', 'user')),
    constraint reports_reason_ck check (reason in ('spam', 'abuse', 'sexual', 'violence', 'other'))
);
create index reports_open_idx on reports (created_at) where resolved_at is null;

-- 비밀번호 찾기: 메일로 보낸 6자리 코드 (해시만 저장). 사람마다 하나, 15분 동안, 5번까지 틀릴 수 있다.
create table password_resets (
    user_id    bigint       primary key references users (id) on delete cascade,
    code_hash  varchar(100) not null,
    expires_at timestamptz  not null,
    attempts   int          not null default 0,
    sent_at    timestamptz  not null
);

-- 로그인 토큰에 이 번호가 들어간다. 비밀번호를 바꾸면 1 올라가서 그 전에 받은 로그인은 모두 끝난다 (다른 기기 포함).
alter table users add column token_version int not null default 0;
